services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: php-programming
    restart: always
    working_dir: /var/www/
    volumes:
      - ../src:/var/www
  nginx:
    image: nginx:1.21.1-alpine
    container_name: nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d
